# Use root/example as user/password credentials
version: '3.1'

services:
    db:
        image: "library/mysql:8.0"
        ports:
            - '3310:3306'
        volumes:
            - "./docker/mysql/:/var/lib/mysql/"
        environment:
            - MYSQL_USER=user
            - MYSQL_PASSWORD=1234
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=1234