version: '3.3'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=1234"
      - "MYSQL_DATABASE=test"
    ports:
      - "3308:3306"